In [ ]:
# 1
import torch

# Create a tensor
x = torch.arange(1, 9)

# Reshape the tensor to a 2x4 matrix
reshaped_x = x.view(2, 4)

print("Original Tensor:")
print(x)
print("\nReshaped Tensor:")
print(reshaped_x)


Original Tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8])

Reshaped Tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# Resize the tensor to a 3x3 matrix, discarding or copying elements if necessary
resized_x = x.resize_(3, 2)

print("Resized Tensor:")
print(resized_x)


Resized Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
# Create a tensor with a singleton dimension
y = torch.randn(1, 3, 1, 4)

# Squeeze the tensor to remove singleton dimensions
squeezed_y = y.squeeze()

print("Original Tensor:")
print(y.size())
print("\nSqueezed Tensor:")
print(squeezed_y.size(),)


Original Tensor:
torch.Size([1, 3, 1, 4])

Squeezed Tensor:
torch.Size([3, 4])


In [ ]:
import torch

# Create two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Stack the tensors along a new dimension (default is dim=0)
stacked_tensor = torch.stack([tensor1, tensor2])

print("Original Tensor 1:")
print(tensor1)

print("\nOriginal Tensor 2:")
print(tensor2)

print("\nStacked Tensor:")
print(stacked_tensor)


Original Tensor 1:
tensor([1, 2, 3])

Original Tensor 2:
tensor([4, 5, 6])

Stacked Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Unsqueeze the tensor along the first dimension
unsqueezed_y = squeezed_y.unsqueeze(0)

print("Original Tensor:")
print(squeezed_y.size())
print("\nUnsqueezed Tensor:")
print(unsqueezed_y.size())


Original Tensor:
torch.Size([3, 4])

Unsqueezed Tensor:
torch.Size([1, 3, 4])


In [ ]:
# 2
# Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print("Original 3D Tensor:")
print(tensor_3d)
print("Original Tensor Shape:", tensor_3d.shape)

# Permute the dimensions
permuted_tensor_3d = tensor_3d.permute(2, 0, 1)

print("\nPermuted 3D Tensor:")
print(permuted_tensor_3d)
print("Permuted Tensor Shape:", permuted_tensor_3d.shape)


Original 3D Tensor:
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
Original Tensor Shape: torch.Size([3, 2, 2])

Permuted 3D Tensor:
tensor([[[ 1,  3],
         [ 5,  7],
         [ 9, 11]],

        [[ 2,  4],
         [ 6,  8],
         [10, 12]]])
Permuted Tensor Shape: torch.Size([2, 3, 2])


In [ ]:
# 3
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access a specific element
element = tensor[1, 2]
print("Element at index (1, 2):", element)

# Access a whole row or column
row = tensor[1, :]
column = tensor[:, 2]

print("\nRow at index 1:")
print(row)

print("\nColumn at index 2:")
print(column)


Element at index (1, 2): tensor(6)

Row at index 1:
tensor([4, 5, 6])

Column at index 2:
tensor([3, 6, 9])


In [ ]:
# 4
import numpy as np
import torch

# Create a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
torch_tensor = torch.from_numpy(numpy_array)

print("NumPy Array:")
print(numpy_array)

print("\nPyTorch Tensor:")
print(torch_tensor)
# Convert PyTorch tensor to NumPy array
numpy_array_back = torch_tensor.numpy()


print("\nNumPy Array:")
print(numpy_array_back)


NumPy Array:
[[1 2 3]
 [4 5 6]]

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

NumPy Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# 5
import torch

# Create a random tensor of size 7x7
random_tensor = torch.randn(7, 7)

print("Random Tensor of Size 7x7:")
print(random_tensor)


Random Tensor of Size 7x7:
tensor([[ 1.1116,  0.8983, -0.5236,  2.2763, -0.3374,  1.0498,  0.4906],
        [ 0.1120,  0.9980, -0.3010,  1.0759, -0.7126, -0.0906,  0.8540],
        [ 0.7834,  1.0693, -1.2048,  0.0883,  0.6009,  0.8211, -0.5672],
        [ 0.5749, -1.2088,  0.1611, -1.6035,  0.5991,  0.5905,  2.3432],
        [ 0.0453, -0.9913, -0.1932, -0.0166, -1.0873,  1.1005, -0.7763],
        [-0.4083,  0.9364,  0.3306,  1.1694,  1.7606,  0.1469, -0.3243],
        [-2.3216,  1.6120,  0.6496,  0.3387, -0.0169,  0.2874, -0.1823]])


In [ ]:
# 6
import torch

# Create a random tensor of size 7x7
row_tensor = torch.randn(7, 7)

# Create a tensor of size 7x1
column_tensor = torch.randn(7, 1)

# Multiply the tensors
result_tensor = row_tensor.matmul(column_tensor)

print("row Tensor (7x7):")
print(row_tensor)

print("\nColumn Tensor (7x1):")
print(column_tensor)

print("\nResult Tensor after Multiplication:")
print(result_tensor)


row Tensor (7x7):
tensor([[ 0.9380, -0.2529,  0.8072,  1.2946, -0.1206, -0.1409, -1.3976],
        [ 0.2961, -1.0944,  0.0669,  0.7631,  0.3813, -1.6050, -0.3871],
        [-0.8116, -1.5249,  0.6676,  1.5396, -0.1050,  0.4484,  0.9708],
        [ 0.0905,  0.1431,  2.4081, -0.0931, -0.0296,  0.5167,  0.8063],
        [-1.9213, -0.9025,  1.7194,  1.2070,  0.5626, -0.6492,  0.4772],
        [-0.1050, -0.9342, -1.8059, -0.1685, -1.8332,  1.4625, -0.0041],
        [-1.1506,  0.7972, -1.6275,  0.7658, -0.2148,  0.4959, -1.2545]])

Column Tensor (7x1):
tensor([[-1.5262],
        [-0.1260],
        [ 0.3673],
        [ 1.4186],
        [ 0.6303],
        [-0.4748],
        [-0.3896]])

Result Tensor after Multiplication:
tensor([[ 1.2689],
        [ 1.9463],
        [ 3.2027],
        [ 0.0181],
        [ 5.8665],
        [-2.4725],
        [ 2.2621]])


In [ ]:
# 7
import torch

# Create two tensors on the CPU
tensor1 = torch.randn((2, 3))
tensor2 = torch.randn((2, 3))

# Check the device of the tensors (should be 'cpu' initially)
print("Tensor 1 Device:", tensor1.device)
print("Tensor 2 Device:", tensor2.device)

# Move the tensors to the GPU (assuming a GPU is available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

# Check the device of the tensors after moving to GPU
print("\nAfter Moving to GPU:")
print("Tensor 1 Device:", tensor1.device)
print("Tensor 2 Device:", tensor2.device)


Tensor 1 Device: cpu
Tensor 2 Device: cpu

After Moving to GPU:
Tensor 1 Device: cuda:0
Tensor 2 Device: cuda:0


In [ ]:
# 9 and 10
import torch

# Create a random tensor of size 7x7
tensor_7x7 = torch.randn(7, 7)

# Create a random tensor of size 7x1
column_tensor = torch.randn(7, 1)

# Perform matrix multiplication
result_tensor = tensor_7x7.matmul(column_tensor)

# Find max and min in the 7x7 tensor
max_value_7x7 = torch.max(tensor_7x7)
min_value_7x7 = torch.min(tensor_7x7)

# Find max and min in the result tensor
max_value_result = torch.max(result_tensor)
min_value_result = torch.min(result_tensor)

print("Max value in the 7x7 tensor:", max_value_7x7.item())
print("Min value in the 7x7 tensor:", min_value_7x7.item())

print("\nMax value in the result tensor:", max_value_result.item())
print("Min value in the result tensor:", min_value_result.item())


Max value in the 7x7 tensor: 2.1846022605895996
Min value in the 7x7 tensor: -1.9242759943008423

Max value in the result tensor: 4.181865692138672
Min value in the result tensor: -4.148242950439453


In [ ]:
import torch

# Set seed for reproducibility
torch.manual_seed(7)

# Create a random tensor of size (1, 1, 1, 10)
tensor_original = torch.randn(1, 1, 1, 10)

# Remove all dimensions of size 1
tensor_removed_dims = tensor_original.squeeze()

# Print the dimensions of both tensors
print("Original Tensor Size:", tensor_original.size())
print("Tensor after Removing Dimensions of Size 1:", tensor_removed_dims.size())


Original Tensor Size: torch.Size([1, 1, 1, 10])
Tensor after Removing Dimensions of Size 1: torch.Size([10])
